FROM public.ecr.aws/degica/rails-buildpack:2.7.7

ARG DOCKER_UID=1000
ARG APP_HOME

RUN useradd --uid $DOCKER_UID --user-group --create-home app
RUN mkdir -p $APP_HOME && chown -R app:app $APP_HOME
RUN ln -s -f /app $APP_HOME

RUN apt-get install -y openssh-client --no-install-recommends

WORKDIR /app
RUN rm -rf $APP_HOME && ln -s /app $APP_HOME
ENV PATH=/app/bin:$PATH
ENV HOME=/home/app

USER app
